// src/components/ui/Badge.tsx
import type { ReactNode } from 'react'

export interface BadgeProps {
  children: ReactNode
  variant?:
    | 'default'
    | 'primary'
    | 'accent'
    | 'outline'
    | 'success'
    | 'warning'
    | 'error'
  className?: string
}

export function Badge({
  children,
  variant = 'default',
  className = '',
}: BadgeProps) {
  const variants = {
    default: 'bg-[var(--color-accent-bg)] text-[var(--color-accent)]',
    primary: 'bg-[var(--color-accent)] text-[var(--color-surface)]',
    accent: 'bg-[var(--color-accent)] text-[var(--color-surface)]',
    outline:
      'border border-[var(--color-border-on-surface)] text-[var(--color-text-on-surface-secondary)]',
    success: 'bg-[var(--color-success-bg)] text-[var(--color-success)]',
    warning: 'bg-[var(--color-warning-bg)] text-[var(--color-warning)]',
    error: 'bg-[var(--color-error-bg)] text-[var(--color-error)]',
  }

  return (
    <span
      className={`inline-flex items-center rounded-full px-2 py-0.5 text-xs font-medium ${variants[variant]} ${className}`}
    >
      {children}
    </span>
  )
}

// apps/web/src/lib/components/Badge.svelte
<script lang="ts">
	import type { Snippet } from 'svelte';

	interface Props {
		variant?: 'default' | 'success' | 'warning' | 'error' | 'info';
		children: Snippet;
	}

	let { variant = 'default', children }: Props = $props();

	const variants = {
		default: 'bg-[var(--color-primary-bg)] text-[var(--color-primary-light)]',
		success: 'bg-[var(--color-success-bg)] text-[var(--color-success)]',
		warning: 'bg-[var(--color-warning-bg)] text-[var(--color-warning)]',
		error: 'bg-[var(--color-error-bg)] text-[var(--color-error)]',
		info: 'bg-[var(--color-info-bg)] text-[var(--color-info)]'
	};
</script>

<span class="inline-flex items-center rounded-full px-2.5 py-0.5 text-xs font-medium {variants[variant]}">
	{@render children()}
</span>
