// apps/web/src/lib/components/EmptyState.svelte
<script lang="ts">
	import type { Snippet, Component } from 'svelte';
	import type { LucideProps } from '@lucide/svelte';

	interface Props {
		icon?: Component<LucideProps>;
		title: string;
		description: string;
		children?: Snippet;
	}

	let { icon: IconComponent, title, description, children }: Props = $props();
</script>

<div
	class="flex flex-col items-center justify-center rounded-2xl border border-[var(--color-border)] bg-[var(--color-bg-elevated)] p-8 text-center"
	role="region"
	aria-label={title}
>
	{#if IconComponent}
		<div class="mb-4 rounded-full bg-[var(--color-primary-bg)] p-3">
			<IconComponent class="h-6 w-6 text-[var(--color-primary)]" aria-hidden="true" />
		</div>
	{/if}
	<h3 class="text-lg font-semibold" style="color: var(--color-heading);">
		{title}
	</h3>
	<p class="mt-1 max-w-sm text-sm" style="color: var(--color-text-secondary);">
		{description}
	</p>
	{#if children}
		<div class="mt-5">
			{@render children()}
		</div>
	{/if}
</div>

// prototype/src/components/ui/EmptyState.tsx
import type { ReactNode } from 'react'
import { Surface } from './Surface'
import { Heading } from './Heading'
import { Text } from './Text'
import { Stack } from './Stack'

export interface EmptyStateProps {
  icon?: ReactNode
  title: string
  description?: string
  action?: ReactNode
  className?: string
}

export function EmptyState({
  icon,
  title,
  description,
  action,
  className = '',
}: EmptyStateProps) {
  return (
    <Surface className={`flex flex-col items-center justify-center px-6 py-16 text-center ${className}`}>
      <Stack gap={4} align="center">
        {icon && (
          <div className="flex h-14 w-14 shrink-0 items-center justify-center rounded-full bg-[var(--color-accent-bg)]">
            {icon}
          </div>
        )}

        <Stack gap={1} align="center">
          <Heading level={3} variant="title" onSurface>
            {title}
          </Heading>
          {description && (
            <Text variant="body" onSurface className="max-w-xs">
              {description}
            </Text>
          )}
        </Stack>

        {action}
      </Stack>
    </Surface>
  )
}
